---

- name: Install wget
  yum:
    name: wget
    state: latest

- name: Install git
  yum:
    name: git
    state: latest

- name: Install ansible
  yum:
    name: ansible-2.9.17
    state: present

- name: Install Terraform
  yum:
    name: terraform
    state: latest

- name: Install google-cloud-sdk
  yum:
    name: google-cloud-sdk
    state: latest

- name: Install socat
  yum:
    name: socat
    state: latest

- name: Install bzip2
  yum:
    name: bzip2
    state: latest

- name: Install gcc
  yum:
    name: gcc
    state: latest

- name: Install make
  yum:
    name: make
    state: latest

- name: Install perl
  yum:
    name: perl
    state: latest

- name: Install kernel-headers
  yum:
    name: kernel-headers
    state: latest

- name: Install kernel-devel
  yum:
    name: kernel-devel
    state: latest

- name: Install python
  yum:
    name: python
    state: latest

- name: Install python-pip
  yum:
    name: python-pip
    state: latest

- name: Install python3
  yum:
    name: python3
    state: latest

- name: Install python3-pip
  yum:
    name: python3-pip
    state: latest

- name: Install rsync
  yum:
    name: rsync
    state: latest
